name: check Next.js app

on:
    - pull_request

jobs:
    code-check:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Check'
              run: npm run check:all

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Test'
              run: npx vitest --coverage.enabled true
            - name: 'Report Coverage'
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
